/*
* generated by Xtext
*/
package com.chorusjs.ol;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CordStandaloneSetup extends CordStandaloneSetupGenerated{

	public static void doSetup() {
		new CordStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

